name: Verify project source

on:
  push:
    branches: [ "core" ]
  pull_request:
    branches: [ "core" ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: |
          dart pub global activate fvm
          fvm install
          fvm flutter pub get
      - name: Generate sources
        run: |
          fvm flutter pub run build_runner build --delete-conflicting-outputs
      - name: Verify formatting
        run: |
          fvm dart format --output=none --set-exit-if-changed lib/src
      - name: Analyze project source
        run: |
          fvm flutter analyze --fatal-infos
      - name: Run tests
        run: |
          fvm flutter test
